#!/bin/bash

# Test the connection is closed correctly
# after all data are sent even if real client
# already closed the connection
port1=8765
port2=8764
set -e

if ! nc --help &> /dev/null; then
	echo "This test require netcat to be installed" >&2
	exit 1
fi

# send a file quite long, check all is received
killall latency &> /dev/null || true
nc -4l 127.0.0.1 $port1 > out &
receive=$!
./latency $port2 $port1 10ms 4K &
latency=$!
sleep 0.05
nc -4 127.0.0.1 $port2 < latency
( sleep 5; kill $receive ) &
sleep=$!
disown $sleep
wait $receive
kill $latency || true
kill $sleep || true
if ! cmp out latency; then
	echo "Failure to send all data" >&2
	exit 1
fi
rm out
echo Test succeeded
